# Generated by Django 2.2.15 on 2020-08-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0002_auto_20200827_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('signature', models.BigIntegerField()),
                ('caisse', models.ManyToManyField(blank=True, related_name='coffre_caisse', to='caisse.Caisse')),
            ],
        ),
    ]
